### PR TITLE
FIX import

### PR DESCRIPTION
**Pull request by jasmainak**
Sorry there was a small problem with the last PR. This should fix it.

Also removed some dead code.

### CODE REVIEW

**Comment by blakecaldwell** [comment]
thanks @jasmainak. just in case you had other work in progress, do you think you could hold off for the remainder of today while I fix up the PR?

**Comment by jasmainak** [comment]
sounds good. I won't work on it more today then. Would you mind merging/cherry-picking/copying this code though. You'll need it for it to run.

**Comment by blakecaldwell** [comment]
Thanks. Sure, I'll merge it later this evening.

**Comment by blakecaldwell** [comment]
Feel free to review the code and suggest changes. I should only have minor changes from now on.

**Pull request merged**
