### PR TITLE
[MRG] fix postproc and add default drives to Network

### PR DESCRIPTION
**Pull request by cjayb**
Here's a fix to the issue @jasmainak flagged me on (and another related to 'common' drives

These are both rather hacky. Also, the simulation result doesn't make sense :( Some digging needed to figure out what's going wrong.

### CODE REVIEW

**Comment by cjayb** [comment]
Hmm, gamma-example does look promising though... Something's wrong with the dipole plot panel?

Screenshot 2021-03-12 at 22 25 13

**Comment by jasmainak** [comment]
could it be that the scale is off? That's why you don't see anything ...

**Comment by cjayb** [comment]
> could it be that the scale is off? That's why you don't see anything ...

I guess. I find the plotting logic (with QTCanvas) totally opaque, so I don't know where to go a-searching... Pointers appreciated! Do you get this too (evoked example):

Screenshot 2021-03-13 at 18 06 56

**Comment by blakecaldwell** [comment]
Okay, the plotting issue doesn't happen with the hnn-core commit that I've been using locally: fa9c666c3. I have extremely limited bandwidth, so I won't be investigating that until I'm done with my current in-flight code changes. Thanks for setting up PRs like this one for queuing up changes. You can expect me to follow up in the next week.

I wouldn't waste time on the plotting code in `simdat.py` if you can help it. That file tries to do too many things. It would be amazing if the plotting code was completely removed from that file. However, I'll track down the discrepancy to get something that works with hnn-core master.

**Comment by jasmainak** [comment]
Thanks for sharing the commit hash you've been testing on! 

<s>I think we can use "git bisect" to figure out where things went off</s> (don't waste time on this ... lots of broken commits in the middle

**Comment by jasmainak** [comment]
Okay I don't think problem is in HNN plotting. Here is script to reproduce @cjayb :)

```py
params = {
    "L2Basket_Gauss_A_weight": 0.0,
    "L2Basket_Gauss_mu": 2000.0,
    "L2Basket_Gauss_sigma": 3.6,
    "L2Basket_Pois_A_weight_ampa": 0.0,
    "L2Basket_Pois_A_weight_nmda": 0.0,
    "L2Basket_Pois_lamtha": 0.0,
    "L2Pyr_Gauss_A_weight": 0.0,
    "L2Pyr_Gauss_mu": 2000.0,
    "L2Pyr_Gauss_sigma": 3.6,
    "L2Pyr_Pois_A_weight_ampa": 0.0,
    "L2Pyr_Pois_A_weight_nmda": 0.0,
    "L2Pyr_Pois_lamtha": 0.0,
    "L2Pyr_ampa_e": 0.0,
    "L2Pyr_ampa_tau1": 0.5,
    "L2Pyr_ampa_tau2": 5.0,
    "L2Pyr_apical1_L": 306.0,
    "L2Pyr_apical1_diam": 4.08,
    "L2Pyr_apicaloblique_L": 340.0,
    "L2Pyr_apicaloblique_diam": 3.91,
    "L2Pyr_apicaltrunk_L": 59.5,
    "L2Pyr_apicaltrunk_diam": 4.25,
    "L2Pyr_apicaltuft_L": 238.0,
    "L2Pyr_apicaltuft_diam": 3.4,
    "L2Pyr_basal1_L": 85.0,
    "L2Pyr_basal1_diam": 4.25,
    "L2Pyr_basal2_L": 255.0,
    "L2Pyr_basal2_diam": 2.72,
    "L2Pyr_basal3_L": 255.0,
    "L2Pyr_basal3_diam": 2.72,
    "L2Pyr_dend_Ra": 200.0,
    "L2Pyr_dend_cm": 0.6195,
    "L2Pyr_dend_el_hh2": -65.0,
    "L2Pyr_dend_gbar_km": 250.0,
    "L2Pyr_dend_gkbar_hh2": 0.01,
    "L2Pyr_dend_gl_hh2": 4.26e-05,
    "L2Pyr_dend_gnabar_hh2": 0.15,
    "L2Pyr_gabaa_e": -80.0,
    "L2Pyr_gabaa_tau1": 0.5,
    "L2Pyr_gabaa_tau2": 5.0,
    "L2Pyr_gabab_e": -80.0,
    "L2Pyr_gabab_tau1": 1.0,
    "L2Pyr_gabab_tau2": 20.0,
    "L2Pyr_nmda_e": 0.0,
    "L2Pyr_nmda_tau1": 1.0,
    "L2Pyr_nmda_tau2": 20.0,
    "L2Pyr_soma_L": 22.1,
    "L2Pyr_soma_Ra": 200.0,
    "L2Pyr_soma_cm": 0.6195,
    "L2Pyr_soma_diam": 23.4,
    "L2Pyr_soma_el_hh2": -65.0,
    "L2Pyr_soma_gbar_km": 250.0,
    "L2Pyr_soma_gkbar_hh2": 0.01,
    "L2Pyr_soma_gl_hh2": 4.26e-05,
    "L2Pyr_soma_gnabar_hh2": 0.18,
    "L5Basket_Gauss_A_weight": 0.0,
    "L5Basket_Gauss_mu": 2000.0,
    "L5Basket_Gauss_sigma": 2.0,
    "L5Basket_Pois_A_weight_ampa": 0.0,
    "L5Basket_Pois_A_weight_nmda": 0.0,
    "L5Basket_Pois_lamtha": 0.0,
    "L5Pyr_Gauss_A_weight": 0.0,
    "L5Pyr_Gauss_mu": 2000.0,
    "L5Pyr_Gauss_sigma": 4.8,
    "L5Pyr_Pois_A_weight_ampa": 0.0,
    "L5Pyr_Pois_A_weight_nmda": 0.0,
    "L5Pyr_Pois_lamtha": 0.0,
    "L5Pyr_ampa_e": 0.0,
    "L5Pyr_ampa_tau1": 0.5,
    "L5Pyr_ampa_tau2": 5.0,
    "L5Pyr_apical1_L": 680.0,
    "L5Pyr_apical1_diam": 7.48,
    "L5Pyr_apical2_L": 680.0,
    "L5Pyr_apical2_diam": 4.93,
    "L5Pyr_apicaloblique_L": 255.0,
    "L5Pyr_apicaloblique_diam": 5.1,
    "L5Pyr_apicaltrunk_L": 102.0,
    "L5Pyr_apicaltrunk_diam": 10.2,
    "L5Pyr_apicaltuft_L": 425.0,
    "L5Pyr_apicaltuft_diam": 3.4,
    "L5Pyr_basal1_L": 85.0,
    "L5Pyr_basal1_diam": 6.8,
    "L5Pyr_basal2_L": 255.0,
    "L5Pyr_basal2_diam": 8.5,
    "L5Pyr_basal3_L": 255.0,
    "L5Pyr_basal3_diam": 8.5,
    "L5Pyr_dend_Ra": 200.0,
    "L5Pyr_dend_cm": 0.85,
    "L5Pyr_dend_el_hh2": -71.0,
    "L5Pyr_dend_gbar_ar": 1e-06,
    "L5Pyr_dend_gbar_ca": 60.0,
    "L5Pyr_dend_gbar_cat": 0.0002,
    "L5Pyr_dend_gbar_kca": 0.0002,
    "L5Pyr_dend_gbar_km": 200.0,
    "L5Pyr_dend_gkbar_hh2": 0.01,
    "L5Pyr_dend_gl_hh2": 4.26e-05,
    "L5Pyr_dend_gnabar_hh2": 0.14,
    "L5Pyr_dend_taur_cad": 20.0,
    "L5Pyr_gabaa_e": -80.0,
    "L5Pyr_gabaa_tau1": 0.5,
    "L5Pyr_gabaa_tau2": 5.0,
    "L5Pyr_gabab_e": -80.0,
    "L5Pyr_gabab_tau1": 1.0,
    "L5Pyr_gabab_tau2": 20.0,
    "L5Pyr_nmda_e": 0.0,
    "L5Pyr_nmda_tau1": 1.0,
    "L5Pyr_nmda_tau2": 20.0,
    "L5Pyr_soma_L": 39.0,
    "L5Pyr_soma_Ra": 200.0,
    "L5Pyr_soma_cm": 0.85,
    "L5Pyr_soma_diam": 28.9,
    "L5Pyr_soma_el_hh2": -65.0,
    "L5Pyr_soma_gbar_ar": 1e-06,
    "L5Pyr_soma_gbar_ca": 60.0,
    "L5Pyr_soma_gbar_cat": 0.0002,
    "L5Pyr_soma_gbar_kca": 0.0002,
    "L5Pyr_soma_gbar_km": 200.0,
    "L5Pyr_soma_gkbar_hh2": 0.01,
    "L5Pyr_soma_gl_hh2": 4.26e-05,
    "L5Pyr_soma_gnabar_hh2": 0.16,
    "L5Pyr_soma_taur_cad": 20.0,
    "N_pyr_x": 10,
    "N_pyr_y": 10,
    "N_trials": 1,
    "T_pois": 170.0,
    "celsius": 37.0,
    "dipole_scalefctr": 3000,
    "dipole_smooth_win": 30,
    "distribution_dist": "normal",
    "distribution_prox": "normal",
    "dt": 0.025,
    "dt_evprox0_evdist": -1,
    "dt_evprox0_evprox1": -1,
    "events_per_cycle_dist": 2,
    "events_per_cycle_prox": 2,
    "f_input_dist": 10.0,
    "f_input_prox": 10.0,
    "f_max_spec": 100,
    "f_stdev_dist": 20.0,
    "f_stdev_prox": 20.0,
    "gbar_L2Basket_L2Basket": 0.02,
    "gbar_L2Basket_L2Pyr_gabaa": 0.05,
    "gbar_L2Basket_L2Pyr_gabab": 0.05,
    "gbar_L2Basket_L5Pyr": 0.001,
    "gbar_L2Pyr_L2Basket": 0.0005,
    "gbar_L2Pyr_L2Pyr_ampa": 0.0005,
    "gbar_L2Pyr_L2Pyr_nmda": 0.0005,
    "gbar_L2Pyr_L5Basket": 0.00025,
    "gbar_L2Pyr_L5Pyr": 0.00025,
    "gbar_L5Basket_L5Basket": 0.02,
    "gbar_L5Basket_L5Pyr_gabaa": 0.025,
    "gbar_L5Basket_L5Pyr_gabab": 0.025,
    "gbar_L5Pyr_L5Basket": 0.0005,
    "gbar_L5Pyr_L5Pyr_ampa": 0.0005,
    "gbar_L5Pyr_L5Pyr_nmda": 0.0005,
    "gbar_evdist_1_L2Basket_ampa": 0.006562,
    "gbar_evdist_1_L2Basket_nmda": 0.019482,
    "gbar_evdist_1_L2Pyr_ampa": 7e-06,
    "gbar_evdist_1_L2Pyr_nmda": 0.004317,
    "gbar_evdist_1_L5Pyr_ampa": 0.1423,
    "gbar_evdist_1_L5Pyr_nmda": 0.080074,
    "gbar_evprox_1_L2Basket_ampa": 0.08831,
    "gbar_evprox_1_L2Basket_nmda": 0,
    "gbar_evprox_1_L2Pyr_ampa": 0.01525,
    "gbar_evprox_1_L2Pyr_nmda": 0,
    "gbar_evprox_1_L5Basket_ampa": 0.19934,
    "gbar_evprox_1_L5Basket_nmda": 0,
    "gbar_evprox_1_L5Pyr_ampa": 0.00865,
    "gbar_evprox_1_L5Pyr_nmda": 0,
    "gbar_evprox_2_L2Basket_ampa": 3e-06,
    "gbar_evprox_2_L2Basket_nmda": 0,
    "gbar_evprox_2_L2Pyr_ampa": 1.43884,
    "gbar_evprox_2_L2Pyr_nmda": 0,
    "gbar_evprox_2_L5Basket_ampa": 0.008958,
    "gbar_evprox_2_L5Basket_nmda": 0,
    "gbar_evprox_2_L5Pyr_ampa": 0.684013,
    "gbar_evprox_2_L5Pyr_nmda": 0,
    "inc_evinput": 0.0,
    "input_dist_A_delay_L2": 5.0,
    "input_dist_A_delay_L5": 5.0,
    "input_dist_A_weight_L2Basket_ampa": 0.0,
    "input_dist_A_weight_L2Basket_nmda": 0.0,
    "input_dist_A_weight_L2Pyr_ampa": 0.0,
    "input_dist_A_weight_L2Pyr_nmda": 0.0,
    "input_dist_A_weight_L5Pyr_ampa": 0.0,
    "input_dist_A_weight_L5Pyr_nmda": 0.0,
    "input_prox_A_delay_L2": 0.1,
    "input_prox_A_delay_L5": 1.0,
    "input_prox_A_weight_L2Basket_ampa": 0.0,
    "input_prox_A_weight_L2Basket_nmda": 0.0,
    "input_prox_A_weight_L2Pyr_ampa": 0.0,
    "input_prox_A_weight_L2Pyr_nmda": 0.0,
    "input_prox_A_weight_L5Basket_ampa": 0.0,
    "input_prox_A_weight_L5Basket_nmda": 0.0,
    "input_prox_A_weight_L5Pyr_ampa": 0.0,
    "input_prox_A_weight_L5Pyr_nmda": 0.0,
    "numspikes_evdist_1": 1,
    "numspikes_evprox_1": 1,
    "numspikes_evprox_2": 1,
    "prng_seedcore_evdist_1": 4,
    "prng_seedcore_evprox_1": 4,
    "prng_seedcore_evprox_2": 4,
    "prng_seedcore_extgauss": 4,
    "prng_seedcore_extpois": 4,
    "prng_seedcore_input_dist": 4,
    "prng_seedcore_input_prox": 4,
    "record_isoma": 0,
    "record_vsoma": 0,
    "repeats_dist": 10,
    "repeats_prox": 10,
    "save_dpl": 0,
    "save_figs": 0,
    "save_spec_data": 0,
    "sigma_t_evdist_1": 3.85,
    "sigma_t_evprox_1": 2.47,
    "sigma_t_evprox_2": 8.33,
    "sim_prefix": "default",
    "spec_cmap": "jet",
    "sync_evinput": 0,
    "t0_input_dist": 1000,
    "t0_input_prox": 1000.0,
    "t0_input_stdev_dist": 0.0,
    "t0_input_stdev_prox": 0.0,
    "t0_pois": 0.0,
    "t_evdist_1": 63.53,
    "t_evprox_1": 26.61,
    "t_evprox_2": 137.12,
    "threshold": 0.0,
    "tstop": 170,
    "tstop_input_dist": 1001,
    "tstop_input_prox": 1001
}

from hnn_core import Network, simulate_dipole

net = Network(params, add_drives_from_params=True)
dpls = simulate_dipole(net, params['N_trials'], postproc=False)
dpls[0]._baseline_renormalize(params['N_pyr_x'], params['N_pyr_y'])
dpls[0]._convert_fAm_to_nAm() 
dpls[0].smooth(window_len=params['dipole_smooth_win']) 
dpls[0].plot()
```

**Comment by cjayb** [comment]
Thanks @jasmainak , that helped. So quickly I forgot that I decided to include the `baseline_renormalize` and `convert-to-nAm` methods implicitly into `simulate_dipole`... So 'post-processing' only entails smoothing and scaling. This PR should at least keep us moving until the next hurdle. Ready to merge on my end (reviews welcome). The bit about `'common'` vs. `burstyN`-drives is not pretty, but I don't feel it's worth putting effort into the legacy code.

**Review by jasmainak — APPROVED** [review]

**Comment by jasmainak** [comment]
LGTM. Great that you don't use private methods any more!

**Comment by blakecaldwell** [comment]
LGTM, thanks for these updates!

**Pull request merged**
